spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/test_oop
spring.datasource.username=postgres
spring.datasource.password=secret
spring.sql.init.platform=postgres
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
# show SQL queries
spring.jpa.show-sql=true
# set port
server.port=8080
# secret
jwt.secret=P1q7hGFR7haMJwHez66kwIoM5gmsNDrykfg8oxgzKm9
# email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=playworthy.noreply@gmail.com
spring.mail.password=tlmafdbirkiuppqr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true