@userId = 23fb1141-5cc9-4996-8a36-b855f060d9bb
@gameId = 49f6960b-c005-471a-b564-9a70587c625f

### 1. THE REVIEW BOMB ATTEMPT (This SHOULD FAIL with your custom error)
# Note: Change the URL to whatever your Review creation endpoint is!
POST http://localhost:8080/reviews
Content-Type: application/json

{
  "authorId": "{{userId}}",
  "gameId": "{{gameId}}",
  "score": 1,
  "comment": "This game is terrible! I totally played it!"
}


### 2. BUY THE GAME / ADD TO LIBRARY (This should succeed)
# Note: No JSON body is needed here!
POST http://localhost:8080/person/{{userId}}/games/{{gameId}}
Content-Type: application/json


### 3. THE VALID REVIEW (This SHOULD SUCCEED now that they own it)
POST http://localhost:8080/reviews
Content-Type: application/json

{
  "authorId": "{{userId}}",
  "gameId": "{{gameId}}",
  "score": 1,
  "comment": "This game is terrible! I totally played it!"
}